spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blade_calculator
    username: woong
    password: Jhan00254!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
    check-template-location: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: djwxiRp1DdiLXLj2zGlm
            client-secret: TXGOmc3gHz
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        jdbc: debug